# Generated by Django 3.0.7 on 2023-12-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
