# Generated by Django 3.0.7 on 2023-12-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
