# Generated by Django 3.0.7 on 2023-12-18 10:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20231210_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Круиз-контроль', 'Круиз-контроль'), ('Аудиоинтерфейс', 'Аудиоинтерфейс'), ('Подушки безопасности', 'Подушки безопасности'), ('Кондиционер', 'Кондиционирование воздуха'), ('Подогрев сидений', 'Подогрев сидений'), ('Сигнализация', 'Система охранной сигнализации'), ('Парковщик', 'Парковщик'), ('Гидроусилитель руля', 'Гидроусилитель рулевого управления'), ('Камера заднего вида', 'Камера заднего вида'), ('Непосредственный впрыск топлива', 'Непосредственный впрыск топлива'), ('Автоматический запуск/остановка', 'Автоматический запуск/остановка'), ('Ветроотражатель', 'Ветроотражатель'), ('Bluetooth', 'Bluetooth')], max_length=232),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KZ', 'Qazaqstan')], max_length=100),
        ),
    ]
