# Generated by Django 3.0.7 on 2023-12-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20231218_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='city',
        ),
    ]
