# Generated by Django 3.0.7 on 2023-12-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
