# Generated by Django 3.0.7 on 2023-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20231218_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Жезказган', 'йazaqstan')], max_length=100),
        ),
    ]
