# Generated by Django 3.0.7 on 2023-12-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_customer_feedback_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='Car',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
